UPDATE `cunkebao`.`EventTrigger` SET `sName` = '再次添加好友', `jEventHandler` = '[\r\n    {\r\n        \"id\": \"MarkFriendLabel\",\r\n        \"name\": \"打上好友标签\"\r\n    }\r\n]' WHERE `sId` = 'friendreqtask-addfriend-isfriend';
UPDATE `cunkebao`.`EventTrigger` SET `sName` = '添加好友申请发送失败', `jEventHandler` = '[]' WHERE `sId` = 'friendreqtask-addfriend-req-fail';
UPDATE `cunkebao`.`EventTrigger` SET `sName` = '申请已通过为好友', `jEventHandler` = '[\r\n    {\r\n        \"id\": \"handleAddFriendReqPass\",\r\n        \"name\": \"处理成为好友\"\r\n    },\r\n    {\r\n        \"id\": \"UpdateFriendRequestTaskStatus\",\r\n        \"name\": \"更新加友计划状态\"\r\n    },\r\n    {\r\n        \"id\": \"MarkFriendLabel\",\r\n        \"name\": \"打上好友标签\"\r\n    },\r\n    {\r\n        \"id\": \"handleUserIncome\",\r\n        \"name\": \"用户收益\"\r\n    }\r\n]' WHERE `sId` = 'friendreqtask-addfriend-req-pass';
UPDATE `cunkebao`.`EventTrigger` SET `sName` = '添加好友申请发送成功', `jEventHandler` = '[]' WHERE `sId` = 'friendreqtask-addfriend-req-success';
UPDATE `cunkebao`.`EventTrigger` SET `sName` = '申请添加好友', `jEventHandler` = '[\r\n    {\r\n        \"id\": \"UpdateFriendRequestTaskStatus\",\r\n        \"name\": \"更新加友计划状态\"\r\n    },\r\n    {\r\n        \"id\": \"MarkFriendLabel\",\r\n        \"name\": \"打上好友标签\"\r\n    }\r\n]' WHERE `sId` = 'friendreqtask-addfriend-send';
UPDATE `cunkebao`.`EventTrigger` SET `sName` = '首次获得手机号', `jEventHandler` = '[\r\n    {\r\n        \"id\": \"UpdateFriendRequestTaskStatus\",\r\n        \"name\": \"更新加友计划状态\"\r\n    },\r\n    {\r\n        \"id\": \"MarkFriendLabel\",\r\n        \"name\": \"打上好友标签\"\r\n    }\r\n]' WHERE `sId` = 'friendreqtask-getphone-fromfrontend-once';
UPDATE `cunkebao`.`EventTrigger` SET `sName` = '重复获得手机号', `jEventHandler` = '[\r\n    {\r\n        \"id\": \"UpdateFriendRequestTaskStatus\",\r\n        \"name\": \"更新加友计划状态\"\r\n    },\r\n    {\r\n        \"id\": \"MarkFriendLabel\",\r\n        \"name\": \"打上好友标签\"\r\n    }\r\n]' WHERE `sId` = 'friendreqtask-getphone-fromfrontend-repeat';
UPDATE `cunkebao`.`EventTrigger` SET `sName` = '加友计划保存', `jEventHandler` = '[\r\n    {\r\n        \"id\": \"UpdateFriendRequestTaskConfig\",\r\n        \"name\": \"更新加友计划的任务配置\"\r\n    },\r\n    {\r\n        \"id\": \"UpdateFriendRequestTaskStatus\",\r\n        \"name\": \"更新加友计划状态\"\r\n    }\r\n]' WHERE `sId` = 'friendreqtasksave';
UPDATE `cunkebao`.`EventTrigger` SET `sName` = '内容库新建或者编辑保存', `jEventHandler` = '[\r\n    {\r\n        \"id\": \"CollectCfgPush\",\r\n        \"name\": \"采集对象推送到触客端\"\r\n    },\r\n    {\r\n        \"id\": \"MaterialFliterByKeyword\",\r\n        \"name\": \"通过关键字过滤内容库里的内容\"\r\n    }\r\n]' WHERE `sId` = 'materiallibsave';
